### **** Car module ****

### Create a category

POST http://localhost:3333/categories HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "name": "SUV",
  "description": "Categoria de carro SUV"
}

### Import categories from a csv file

POST http://localhost:3333/categories/import HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="arquivo.csv"
Content-Type: text/csv

< ./arquivo.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### List all categories

GET http://localhost:3333/categories HTTP/1.1
Content-Type: application/json; charset=utf-8

### Create a specification

POST http://localhost:3333/specifications HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "name": "Câmbio automático",
  "description": "Carro com câmbio automático"
}

### List all specifications

GET http://localhost:3333/specifications HTTP/1.1
Content-Type: application/json; charset=utf-8

### 

### **** Car module ****

### Create a user

POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "name": "Helena",
  "email": "exemple@gmail.com",
  "password": "123456",
  "driver_license": "12345678"
}

###
