version: "3.8"

services:
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: rentalx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379

volumes:
  pgdata:
    driver: local